name: "Test Setup Edgee Action"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Setup Edgee Action
        uses: ./
